import './App.css'
import {useState} from "react";
import Keypad from "./components/Keypad.jsx";
import keys from "./components/keys.js";
function App() {
    const [gameType, setGameType] = useState('Weekly');
    const [solution, setSolution] = useState('Barendrecht');
    const [scrambledSolution, setScrambledSolution] = useState('Rech te brand');
    const [dropdownOpen, setDropdownOpen] = useState(false);
    const [guesses, setGuesses] = useState(['', '', '', '', '']);
    const [currentGuess, setCurrentGuess] = useState('');


    const handleKeypadInput = (keyValue) => {
        if (keyValue === 'ENTER') {
            handleGuessSubmit();
        } else if (keyValue === '⌫') {
            setCurrentGuess((prev) => prev.slice(0, -1));
        } else {

            if (currentGuess.length < 22) { // Longest station name is 21 chars "Den Haag Laan van NOI"
                setCurrentGuess((prev) => prev + keyValue);
            }
        }
    };

    const guessList = [];
    for (let i = 0; i < guesses.length; i++) {

        const isSubmittedGuess = guesses[i] !== '';
        const isCorrect = isSubmittedGuess && guesses[i].toUpperCase() === solution.toUpperCase();
        const isIncorrect = isSubmittedGuess && guesses[i].toUpperCase() !== solution.toUpperCase();

        const isCurrentInputRow = !isSubmittedGuess && guesses.slice(0, i).every(g => g !== '');

        guessList.push(
            <div key={i} className="guess">
                <span className={`guess-circle ${isIncorrect ? 'incorrect' : ''} ${isCorrect ? 'correct' : ''}`}></span>
                {isCurrentInputRow ? (
                    <input
                        type="text"
                        className="guess-input"
                        value={currentGuess}
                        onChange={e => setCurrentGuess(e.target.value)}
                        onKeyDown={e => {
                            if (e.key === 'Enter') handleGuessSubmit();
                        }}
                        autoFocus
                    />
                ) : (
                    <span className="guessText">{guesses[i]}</span>
                )}
            </div>
        );
    }


    function handleGuessSubmit() {
        if (currentGuess.trim() === '') {
            return;
        }

        if (currentGuess.toUpperCase() === solution.toUpperCase()){
            console.log("You win!");
            /*TODO implement some type of winning scene*/
            return;
        }


        const firstEmptyIndex = guesses.indexOf('');
        if (firstEmptyIndex === -1) {
            console.log("No more guesses left!");
            // TODO: Implement game over logic
            return;
        }

        setGuesses(prevGuesses => {
            const newGuesses = [...prevGuesses];
            newGuesses[firstEmptyIndex] = currentGuess;
            return newGuesses;
        });
        setCurrentGuess('');
    }

    function toggleDropdown() {
        setDropdownOpen(!dropdownOpen);
    }



    function handleSetScrambledSolution() {
        /*TODO once a day || if playing unlimited then every new game */
        /*TODO get scrambled solution from a json file generated by AI*/
        setScrambledSolution('');

        /*TODO get the correct solution corresponding to the scrambled solution also from the json*/
        setSolution('');

    }

    function handleGameTypeChange(gameTypeClicked) {
        if (gameTypeClicked === 'Weekly') {
            setGameType('Weekly');
        } else {
            setGameType('Unlimited');
        }
        setDropdownOpen(false);
    }

    return (
        <div className="App">

            <div className="game">
                {/*Top Bar with logo and gameType*/}
                <div className="topbar">

                    {/*The logo svg*/}
                    <img src="/logo.svg" alt="logo"/>

                    {/*The dropdown for gameType*/}
                    <div className="gameType">
                        <button onClick={toggleDropdown}>
                            <img src="/down_arrow.svg" alt="down_arrow"/>

                        </button>
                        {gameType}
                        {dropdownOpen && (
                            <div className="dropdown-content">
                                <a href="#" onClick={(e) => {
                                    e.preventDefault();
                                    handleGameTypeChange('Weekly');
                                }}>Weekly</a>
                                <a href="#" onClick={(e) => {
                                    e.preventDefault();
                                    handleGameTypeChange('Unlimited');
                                }}>Unlimited</a>
                            </div>
                        )}
                    </div>

                </div>

                {/*The station to guess*/}
                <div className="wordToGuess">{scrambledSolution}</div>

                {/*Your guesses*/}
                <div className="guessList">
                    {guessList}
                </div>

            </div>


            <div className="keyboard">
                <Keypad keys={keys} onKeyClick={handleKeypadInput} />
            </div>
        </div>
    )
}

export default App
